add roadmap subpage, organize pages in folder
OpenFn/docs pull request #194
Opened 2021-06-28 14:29 UTC by ritazagoni

2021-06-28 14:39 UTC, taylordowns2000 requested changes
Hey @ritazagoni , can you revert the filename changes for "for-devs" and "gsoc"? We've got external links pointing there, so need to keep those the same for now. Otherwise looks good.

2021-06-28 14:48 UTC, ritazagoni commented
@taylordowns2000 thanks, done!

2021-06-30 11:58 UTC, ritazagoni commented
@taylordowns2000 can I merge this after having renamed what you requested?

2021-06-30 11:59 UTC, taylordowns2000 approved these changes

2021-06-30 12:32 UTC, merged