Yarn v4.3.1
OpenFn/docs pull request #507
Opened 2024-06-21 14:11 UTC by josephjclark

Turns out yarn has its own self-versioning strategt now

## QA notes

Can we run some quick QA on this?

 -checkout this branch
- run `yarn install`
- should be no diffs in `yarn.lock`
- `yarn -v` should print 4.3.1?

2024-06-24 09:11 UTC, taylordowns2000 requested changes
ack!

<img width="1031" alt="image" src="https://github.com/OpenFn/docs/assets/8732845/1680ee11-200b-4f46-8a16-72ef1a3c01d8">
<img width="527" alt="image" src="https://github.com/OpenFn/docs/assets/8732845/e59f1b9f-4a4f-41f2-8962-c24a88e5ed1a">

2024-06-24 10:43 UTC, josephjclark commented
When I check out this branch my yarn version immediately changes to 4.3.1.

So I'm not sure why you're on 3.2.3 :thinking: 

Have you run `corepack enable` @taylordowns2000 ? Does that make any difference?

2024-06-24 10:53 UTC, taylordowns2000 commented
just tried with `corepack enable` first and no luck. same diff (and same yarn version.)

i use asdf, would that impact?

2024-06-24 11:00 UTC, josephjclark commented
I'm using asdf too. But yeah it might be a factor. I don't know if an install or reshim makes a difference?

Frustrating issue. I don't care which version we use but I want all developers to be using the same yarn. Which should Just Work :tm: 

I'll run a couple of tests on a second system this afternoon

2024-07-25 12:55 UTC, aleksa-krolls commented
hey @josephjclark what's the status here?

2024-07-26 09:21 UTC, josephjclark commented
This and #506 are closely related

2024-08-07 14:24 UTC, closed without merging